package com.reskiosk.emergency

/** Pre-translated emergency strings. No NLLB at alert time. Fallback to English if key missing. */
object EmergencyStrings {
    fun get(key: String, lang: String): String =
        strings[lang]?.get(key) ?: strings["en"]!![key] ?: key

    fun getRandom(keyBase: String, count: Int, lang: String): String {
        if (count <= 1) return get(keyBase, lang)
        val idx = (1..count).random()
        val key = "${keyBase}_${idx}"
        return get(key, lang)
    }

    private val strings = mapOf(
        "en" to mapOf(
            "confirm_prompt" to "I heard something urgent. Do you need emergency help right now?",
            "confirm_title" to "Do you need emergency help?",
            "confirm_yes" to "YES â€” CALL FOR HELP",
            "confirm_no" to "No â€” cancel",
            "activated" to "Help is on the way. A response team has been notified of your location. Stay where you are. You are not alone.",
            "active_title" to "HELP IS ON THE WAY",
            "active_body" to "A response team has been notified of your location. Stay where you are. You are not alone.",
            "acknowledged_title" to "HELP REQUEST ACKNOWLEDGED",
            "acknowledged_body" to "A staff member has acknowledged your request. Please stay where you are.",
            "resolved_title" to "HELP REQUEST RESOLVED",
            "resolved_body" to "The emergency request was marked resolved. This screen will close shortly.",
            "dismiss" to "Dismiss",
            "sending_alert" to "Sending alert...",
            "help_on_the_way" to "Help is on the way.",
            "responding_body" to "Stay here. Responders are coming.",
            "could_not_reach_hub" to "Could not reach emergency system -- retrying.",
            "retrying_attempt" to "Retrying... attempt {n} of {max}.",
            "cancel_false_alarm" to "Cancel -- not an emergency",
            "listening" to "Listening...",
            "preparing" to "Preparing...",
            "recording_too_short" to "Recording was too short. Please hold the button longer.",
            "didnt_hear" to "I didn't hear anything. Please try again.",
            "didnt_catch" to "I didn't catch that. Please try again.",
            "feedback_inaccurate" to "Response is inaccurate",
            "retrieving_new_response_1" to "Retrieving new response...",
            "retrieving_new_response_2" to "Generating a new response...",
            "retrieving_new_response_3" to "Looking for a better answer...",
            "retrieving_new_response_4" to "Let me try another response...",
            "retrieving_new_response_5" to "Finding a clearer answer...",
            "session_ending" to "Session ending, thank you for using ResKiosk."
        ),
        "es" to mapOf(
            "confirm_prompt" to "EscuchÃ© algo urgente. Â¿Necesitas ayuda de emergencia ahora mismo?",
            "confirm_title" to "Â¿Necesitas ayuda de emergencia?",
            "confirm_yes" to "SÃ â€” PEDIR AYUDA",
            "confirm_no" to "No â€” cancelar",
            "activated" to "La ayuda estÃ¡ en camino. El equipo de respuesta ha sido notificado de tu ubicaciÃ³n. QuÃ©date donde estÃ¡s. No estÃ¡s solo.",
            "active_title" to "LA AYUDA ESTÃ EN CAMINO",
            "active_body" to "El equipo de respuesta ha sido notificado. QuÃ©date donde estÃ¡s. No estÃ¡s solo.",
            "dismiss" to "Cerrar",
            "sending_alert" to "Enviando alerta...",
            "help_on_the_way" to "La ayuda esta en camino.",
            "could_not_reach_hub" to "No se pudo contactar al sistema de emergencia -- reintentando.",
            "retrying_attempt" to "Reintentando... intento {n} de {max}.",
            "cancel_false_alarm" to "Cancelar -- no es una emergencia",
            "listening" to "Escuchando...",
            "preparing" to "Preparando...",
            "recording_too_short" to "La grabaciÃ³n fue muy corta. MantÃ©n pulsado el botÃ³n mÃ¡s tiempo.",
            "didnt_hear" to "No escuchÃ© nada. Por favor, intÃ©ntalo de nuevo.",
            "didnt_catch" to "No te entendÃ­. Por favor, intÃ©ntalo de nuevo.",
            "feedback_inaccurate" to "La respuesta no es correcta",
            "retrieving_new_response_1" to "Recuperando nueva respuesta...",
            "retrieving_new_response_2" to "Generando una nueva respuesta...",
            "retrieving_new_response_3" to "Buscando una mejor respuesta...",
            "retrieving_new_response_4" to "Voy a intentar otra respuesta...",
            "retrieving_new_response_5" to "Buscando una respuesta mÃ¡s clara...",
            "session_ending" to "Session ending, thank you for using ResKiosk."
        ),
        "de" to mapOf(
            "confirm_prompt" to "I heard something urgent. Do you need emergency help right now?",
            "confirm_title" to "Do you need emergency help?",
            "confirm_yes" to "YES â€” CALL FOR HELP",
            "confirm_no" to "No â€” cancel",
            "activated" to "Help is on the way. A response team has been notified of your location. Stay where you are. You are not alone.",
            "active_title" to "HELP IS ON THE WAY",
            "active_body" to "A response team has been notified of your location. Stay where you are. You are not alone.",
            "dismiss" to "Dismiss",
            "sending_alert" to "Sending alert...",
            "help_on_the_way" to "Help is on the way.",
            "could_not_reach_hub" to "Could not reach emergency system -- retrying.",
            "retrying_attempt" to "Retrying... attempt {n} of {max}.",
            "cancel_false_alarm" to "Cancel -- not an emergency",
            "listening" to "Wird aufgezeichnet...",
            "preparing" to "Wird vorbereitet...",
            "recording_too_short" to "Aufnahme war zu kurz. Bitte halten Sie die Taste lÃ¤nger gedrÃ¼ckt.",
            "didnt_hear" to "Ich habe nichts gehÃ¶rt. Bitte versuchen Sie es erneut.",
            "didnt_catch" to "Das habe ich nicht verstanden. Bitte versuchen Sie es erneut.",
            "feedback_inaccurate" to "Antwort ist ungenau",
            "retrieving_new_response_1" to "Neue Antwort wird abgerufen...",
            "retrieving_new_response_2" to "Eine neue Antwort wird erstellt...",
            "retrieving_new_response_3" to "Suche nach einer besseren Antwort...",
            "retrieving_new_response_4" to "Ich versuche eine andere Antwort...",
            "retrieving_new_response_5" to "Suche nach einer klareren Antwort...",
            "session_ending" to "Session ending, thank you for using ResKiosk."
        ),
        "fr" to mapOf(
            "confirm_prompt" to "I heard something urgent. Do you need emergency help right now?",
            "confirm_title" to "Do you need emergency help?",
            "confirm_yes" to "YES â€” CALL FOR HELP",
            "confirm_no" to "No â€” cancel",
            "activated" to "Help is on the way. A response team has been notified of your location. Stay where you are. You are not alone.",
            "active_title" to "HELP IS ON THE WAY",
            "active_body" to "A response team has been notified of your location. Stay where you are. You are not alone.",
            "dismiss" to "Dismiss",
            "sending_alert" to "Sending alert...",
            "help_on_the_way" to "Help is on the way.",
            "could_not_reach_hub" to "Could not reach emergency system -- retrying.",
            "retrying_attempt" to "Retrying... attempt {n} of {max}.",
            "cancel_false_alarm" to "Cancel -- not an emergency",
            "listening" to "Ã‰coute en cours...",
            "preparing" to "PrÃ©paration...",
            "recording_too_short" to "L'enregistrement Ã©tait trop court. Maintenez le bouton plus longtemps.",
            "didnt_hear" to "Je n'ai rien entendu. Veuillez rÃ©essayer.",
            "didnt_catch" to "Je n'ai pas compris. Veuillez rÃ©essayer.",
            "feedback_inaccurate" to "La rÃ©ponse est inexacte",
            "retrieving_new_response_1" to "RÃ©cupÃ©ration d'une nouvelle rÃ©ponse...",
            "retrieving_new_response_2" to "GÃ©nÃ©ration d'une nouvelle rÃ©ponse...",
            "retrieving_new_response_3" to "Recherche d'une meilleure rÃ©ponse...",
            "retrieving_new_response_4" to "Je vais essayer une autre rÃ©ponse...",
            "retrieving_new_response_5" to "Recherche d'une rÃ©ponse plus claire...",
            "session_ending" to "Session ending, thank you for using ResKiosk."
        ),
        "ja" to mapOf(
            "confirm_prompt" to "ç·Šæ€¥ã®è¨€è‘‰ãŒèžã“ãˆã¾ã—ãŸã€‚ä»Šã™ãåŠ©ã‘ãŒå¿…è¦ã§ã™ã‹ï¼Ÿ",
            "confirm_title" to "ç·Šæ€¥ã®åŠ©ã‘ãŒå¿…è¦ã§ã™ã‹ï¼Ÿ",
            "confirm_yes" to "ã¯ã„ â€” åŠ©ã‘ã‚’å‘¼ã¶",
            "confirm_no" to "ã„ã„ãˆ â€” ã‚­ãƒ£ãƒ³ã‚»ãƒ«",
            "activated" to "åŠ©ã‘ãŒå‘ã‹ã£ã¦ã„ã¾ã™ã€‚å¯¾å¿œãƒãƒ¼ãƒ ã«ã‚ãªãŸã®å ´æ‰€ãŒé€šçŸ¥ã•ã‚Œã¾ã—ãŸã€‚ãã®å ´ã«ã„ã¦ãã ã•ã„ã€‚ä¸€äººã§ã¯ã‚ã‚Šã¾ã›ã‚“ã€‚",
            "active_title" to "åŠ©ã‘ãŒå‘ã‹ã£ã¦ã„ã¾ã™",
            "active_body" to "å¯¾å¿œãƒãƒ¼ãƒ ã«é€šçŸ¥ã—ã¾ã—ãŸã€‚ãã®å ´ã‚’é›¢ã‚Œãªã„ã§ãã ã•ã„ã€‚ä¸€äººã§ã¯ã‚ã‚Šã¾ã›ã‚“ã€‚",
            "dismiss" to "é–‰ã˜ã‚‹",
            "sending_alert" to "Sending alert...",
            "help_on_the_way" to "Help is on the way.",
            "could_not_reach_hub" to "Could not reach emergency system -- retrying.",
            "retrying_attempt" to "Retrying... attempt {n} of {max}.",
            "cancel_false_alarm" to "Cancel -- not an emergency",
            "feedback_inaccurate" to "ã“ã®å›žç­”ã¯æ­£ç¢ºã§ã¯ã‚ã‚Šã¾ã›ã‚“",
            "retrieving_new_response_1" to "æ–°ã—ã„å›žç­”ã‚’å–å¾—ä¸­...",
            "retrieving_new_response_2" to "æ–°ã—ã„å›žç­”ã‚’ä½œæˆä¸­...",
            "retrieving_new_response_3" to "ã‚ˆã‚Šè‰¯ã„å›žç­”ã‚’æŽ¢ã—ã¦ã„ã¾ã™...",
            "retrieving_new_response_4" to "åˆ¥ã®å›žç­”ã‚’è©¦ã—ã¦ã¿ã¾ã™...",
            "retrieving_new_response_5" to "ã‚ˆã‚Šåˆ†ã‹ã‚Šã‚„ã™ã„å›žç­”ã‚’æŽ¢ã—ã¦ã„ã¾ã™...",
            "session_ending" to "Session ending, thank you for using ResKiosk."
        ),
        // Korean/Tagalog removed per supported language set
    )
}
